
name: Next Deployment                                 

on:                                                   
  push:                                               
    branches: [production]
    
  # Cho phép kích hoạt workflow thủ công từ giao diện GitHub Actions trên repository.
  workflow_dispatch:
  
  # Cho phép chạy tự động theo lịch cron. Cấu trúc '*/5 * *' nghĩa là chạy mỗi 5 phút
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:                                                
  deploy:                                             
    runs-on: ubuntu-latest                           
    steps:                                           
    - name: Deploy using ssh                          
      uses: appleboy/ssh-action@master 
      with:                                           
        host: ${{ secrets.HOST }}                     
        username: ${{ secrets.USERNAME }}             
        # password: ${{ secrets.PASSWORD }}          
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22                                      
        script: |
          cd /home/ubuntu/projects/next-deploy-vps || exit 1
          git fetch origin || exit 1
          git checkout production || exit 1
          git pull || exit 1
          npm install || exit 1
          npm run build || (echo "Build failed" && exit 1)
          pm2 reload next-demo || pm2 start npm -- start
    
    # Lấy source code (clone repository) từ repository của chúng ta
    - name: Checkout code
      uses: actions/checkout@v3

    # Cài đặt Python 3.x
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.x
    
    # Chạy file send_email.py
    - name: Run email code
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      run: python send_email.py

    - name: Notify Slack
      run: |
        curl -X POST -H 'Content-type: application/json' \
        -H 'Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN}}' \
        --data "{
          \"channel\":\"nextjs-deploy-vps\",
          \"text\":\"New push to production branch\\n
          Commit message: *${{ github.event.head_commit.message }}*\\n
          Author: *${{ github.event.head_commit.author.name }}*\\n
          URL: ${{ github.event.head_commit.url }}\"
        }" https://slack.com/api/chat.postMessage

    # Mục đích của upload-artifact: 
    # - Lưu trữ các file build để có thể tải xuống sau này
    # - Hữu ích cho việc debug khi deployment thất bại
    # - Cho phép chia sẻ build artifacts giữa các jobs khác nhau
    # - Lưu trữ evidence của mỗi lần build
    # - Trong Actions của github sau khi chạy CI/CD xong nó sẽ có 1 cái link hiển thị đường dẫn cho phép download các file build này về máy tính 
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build                # Tên của artifact
        path: |                           # Đường dẫn đến files/folders cần upload
          .next/                          
          public/                        
          package.json
          package-lock.json
        retention-days: 7                # Số ngày lưu trữ artifact

  download-and-backup:
    runs-on: ubuntu-latest 
    needs: deploy # Đảm bảo chạy sau khi job deploy hoàn tất (Nếu job deploy thất bại thì job download-and-backup sẽ không chạy)
    steps:
    
    # Lấy source code (clone repository) từ repository của chúng ta
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Next.js artifacts
      uses: actions/download-artifact@v4
      with:
        # name: nextjs-build => Phải trùng với tên artifact đã upload ở job trước (job deploy, step Upload build artifacts)
        name: nextjs-build  
        # path: backup-artifacts
        # - Là đường dẫn relative (tương đối) trong workspace của GitHub Actions
        # - Workspace là thư mục tạm thời được tạo ra khi workflow chạy
        # - Ví dụ: nếu workspace là /home/runner/work/my-repo/my-repo, thì backup-artifacts sẽ tạo thành /home/runner/work/my-repo/my-repo/backup-artifacts
        # - Đặt tên path là gì cũng được
        path: backup-artifacts 

    - name: Prepare backup
      # mkdir -p backup-output => Tạo thư mục riêng cho backup để tránh conflict
      # cp -r backup-artifacts/* backup-output/ => Copy files sang thư mục mới trước khi nén
      # cd backup-artifacts => Di chuyển vào thư mục đã chứa files downloaded. Phải match với path ở bước download trước (step Download Next.js artifacts)
      # tar -czf nextjs-backup.tar.gz => Nén tất cả files trong thư mục hiện tại (.) vào file nextjs-backup.tar.gz. File nén sẽ nằm trong thư mục backup-artifacts
      # echo "Backup created at $(date)" >> backup-info.txt =>  Ghi thông tin backup
      run: |
        mkdir -p backup-output
        cp -r backup-artifacts/* backup-output/
        cd backup-artifacts
        tar -czf ../nextjs-backup.tar.gz . || exit 1   
        echo "Backup created at $(date)" >> backup-info.txt
      
    - name: Upload to backup storage
      uses: actions/upload-artifact@v4
      with:
        # name => Tên artifact cho bản backup. $(date +%Y%m%d) sẽ thêm ngày tháng vào tên (ví dụ: nextjs-backup-20240211)
        name: nextjs-backup-$(date +%Y%m%d)  
        # path => Đường dẫn relative đến các files cần upload. Có thể liệt kê nhiều files/folders. Phải match với vị trí thật của files trong workspace (Dựa trên step Prepare backup)
        path: |
          nextjs-backup.tar.gz 
          backup-info.txt
        retention-days: 30    # Số ngày lưu trữ artifact

    - name: Cleanup
      run: |    # Dọn dẹp sau khi hoàn tất
        rm -rf backup-artifacts
        rm -rf backup-output
        rm -f nextjs-backup.tar.gz backup-info.txt

