
name: Next Deployment                                 

on:                                                   
  push:                                               
    branches: [production]
  # Cho phép kích hoạt workflow thủ công từ giao diện GitHub Actions trên repository.
  workflow_dispatch:
  # Cho phép chạy tự động theo lịch cron. Cấu trúc '*/5 * *' nghĩa là chạy mỗi 5 phút
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:                                                
  deploy:                                             
    runs-on: ubuntu-latest                           
    steps:                                           
    - name: Deploy using ssh                          
      uses: appleboy/ssh-action@master 
      with:                                           
        host: ${{ secrets.HOST }}                     
        username: ${{ secrets.USERNAME }}             
        # password: ${{ secrets.PASSWORD }}          
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22                                      
        script: |
          cd /home/ubuntu/projects/next-deploy-vps || exit 1
          git fetch origin || exit 1
          git checkout production || exit 1
          git pull || exit 1
          npm install || exit 1
          npm run build || (echo "Build failed" && exit 1)
          pm2 reload next-demo || pm2 start npm -- start
    
    # Lấy source code (clone repository) từ repository của chúng ta
    - name: Checkout code
      uses: actions/checkout@v2

    # Cài đặt Python 3.x
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.x
    
    # Chạy file send_email.py
    - name: Run email code
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      run: python send_email.py

    - name: Notify Slack
      run: |
        curl -X POST -H 'Content-type: application/json' \
        -H 'Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN}}' \
        --data "{
          \"channel\":\"nextjs-deploy-vps\",
          \"text\":\"New push to production branch\\n
          Commit message: *${{ github.event.head_commit.message }}*\\n
          Author: *${{ github.event.head_commit.author.name }}*\\n
          URL: ${{ github.event.head_commit.url }}\"
        }" https://slack.com/api/chat.postMessage

    # Mục đích của upload-artifact: 
    # - Lưu trữ các file build để có thể tải xuống sau này
    # - Hữu ích cho việc debug khi deployment thất bại
    # - Cho phép chia sẻ build artifacts giữa các jobs khác nhau
    # - Lưu trữ evidence của mỗi lần build
    # - Trong Actions của github sau khi chạy CI/CD xong nó sẽ có 1 cái link hiển thị đường dẫn cho phép download các file build này về máy tính 
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: next-build                  # Tên của artifact
        path: |                           # Đường dẫn đến files/folders cần upload
          .next/                          
          public/                        
          package.json
          package-lock.json
        retention-days: 7                # Số ngày lưu trữ artifact